config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
    sessions: 'users/sessions', 
    registrations: 'users/registrations' 
  }



  root 'home#index'

  get "/dashboard" , to: "home#dashboard" 
  get "/about" , to: "home#about"
  get "/index" , to: "home#index"
  get "/blog" ,  to: "home#blog"
  get "/contact", to: "home#contact"
  get "/pricing", to: "home#pricing"

  
  resources :activities
  resources :member_activities
  resources :trainer_activities

  namespace :purchase do
    resources :checkouts
  end  

  get "success" , to: "purchase/checkouts#success"

  resources :subscriptions

  resources :webhooks, only: :create

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	before_action :get_actvities, only: [:dashboard]

	def index

	end	

	def header
	end
	
	def about
	end

	def confirmation
	end

	def dashboard
		
	end	

	def pricing
	end

	private
		def get_actvities
			@activities = Activity.all
		end
		
		def get_member_activities
		end	
		
end	

app/views/home/_header.html.erb
<div class="container-fluid ">
	
	<div class="row py-2 ">
		
		<div class="col-md-3 py-4 d-flex justify-content-center">
			<nav class="nav">
				<a href="/index" class="nav-link text-white"><%= image_tag "logo.png" %></a>
			</nav>
		</div>

		<div class="col py-4">
			<nav class="nav">
				<a href="/index" class="nav-link text-white fw-bold fs-5">Home</a>
				<a href="/about" class="nav-link text-white fw-bold fs-5">About Us</a>
				<%= link_to "Activity", new_activity_path , class: "nav-link text-white fw-bold fs-5" %>
				<%= link_to "Sign In", new_user_session_path , class: "nav-link text-white fw-bold fs-5"%>
				<% if user_signed_in? %>
					<%= link_to "DashBoard" , dashboard_path ,  class: "nav-link text-white fw-bold fs-5" %> 
					<%= link_to "Edit" , edit_user_registration_path ,  class: "nav-link text-white fw-bold fs-5" %>				
					<%= link_to "Log Out" ,  destroy_user_session_path, method: :delete , data:{confirm:"Do you Want To Logout?"} , class: "nav-link text-white fw-bold fs-5"%>
				<%end%>
			</nav>
		</div>


		<div class="col-md-2 py-4">
			<nav class="nav">
				<a href="https://www.linkedin.com/" class="nav-link"><%= image_tag "In.png", height: 20 %></a>
				<a href="https://www.instagram.com/" class="nav-link"><%= image_tag "ig.png", height: 20 %></a>
				<a href="https://www.twitter.com/" class="nav-link"><%= image_tag "Tw.png", height: 20 %></a>
				
			</nav>
		</div>


	</div>


</div>

app/views/home/about.html.erb
<%= render 'home/header' %>

    
<section class="breadcrumb-section set-bg ">

    <div class="container">
        
        <div class="row">

            <div class="col-lg-12">

                <div class="breadcrumb-text text-white">
                    <h2>About Us</h2>     
                 </div>

            </div>

         </div>

    </div>

</section>

<section class="aboutus-section">

        <div class="container">

            <div class="aboutus-page-text">

                    <div class="row">

                        <div class="col-xl-9 col-lg-10 m-auto">

                        <div class="section-title">

                            <h2 class="text-white">WHO WE ARE & WHAT WE DO</h2>
                            <p class="text-white">CrossFit is a cutting-edge functional fitness system that can help everyday men. There is a significant portion of the population here in North America, that actually want and need success to be hard!</p>

                        </div>

                    </div>
                </div>

                
                <img src="https://technext.github.io/activitar/img/testimonial-bg.jpg" alt="">
                
                <div class="row">
                    
                    <div class="col-lg-6">
                        
                        <div class="about-us py-4">
                            
                            <h4 class="text-white">ABOUT US</h4>
                            
                            <p class="text-white">Having a baby can be a nerve wracking experience for new parents – not the nine months of pregnancy, I’m talking about after the infant is brought home from the hospital. It’s always the same thing, by the time they have their third child they have it all figured out, but with number one it’s a learning thing.</p>

                            <p class="text-white">Baby monitors help you hear your baby’s needs without you having to be in the room with the baby. Some baby monitors are portable, or “mobile” and are small enough that you can carry it in your pocket as you do your daily chores around the house. Depending on your price range it’s best to have a base unit that plugs into the wall. The receiving unit can be like your portable phone, you can carry it around with you, and plug it back into the base unit to be recharged.
                            </p>

                        </div>

                    </div>
                    
                    <div class="col-lg-6">
                        
                        <div class="about-quality py-4">
                            
                            <h4 class="text-white">OUR QUALITY</h4>
                            
                            <p class="text-white">Donec enim ipsum porta justo integer at velna vitae auctor integer congue magna at risus auctor purus unt pretium ligula rutrum integer sapien ultrice ligula luctus undo magna risus </p>
                            
                            <ul class="text-white">
                                <li>Lorem ipsum dolor sitdoni amet,consectetur dont adipis elite vivamus interdum.</li>
                                <li>Integer pulvinar ante nulla, ac fermentum ex congue id vestibulum ensectetur.</li>
                                <li>Proin blandit nibh in quam semper iaculis lorem ipsum dolor salama ender.</li>
                                <li>Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. </li>
                            </ul>

                        </div>

                    </div>

                </div>

            </div>

        </div>

    </section>

app/views/home/blog.html.erb
<%= render '/home/header' %>

<%= "Blog" %>

app/views/home/contact.html.erb
<%= render '/home/header' %>

<%= "Contact" %>

app/views/home/dashboard.html.erb
<div class="container">
	<div class="row">
		<div class="col text-center">
			<h4>Welcome To <%=current_user.type%>DashBoard</h4>
			<br>
		</div>
	</div>
</div>

<h4 class="text-center">ALL ACTIVITIES</h4>

<div class="container">
  <div class="row row-cols-1 row-cols-md-3">
    <% @activities.each do |activity| %>
    <div class="col-md-3">
      <div class="card" style="width: 15rem;">
        <div class="card-body">
          <h5 class="card-title"> <%= activity.name %></h5>
          <p class="card-text"><%= activity.description%><br></p>
          <a href="#" class="btn btn-primary">JOIN</a>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<%= render 'home/header'%> 	


<div class="container-home set-bg">
	
	<div class="container">

		<div class="row ">
			<div class="col-lg-12 text-white py-2">
				<div class="home-section ">
				<h2 class="fw-light">JOIN US NOW</h2>
				<h3 class="fw-bolder">FITNESS & SPORT</h3>
				<button type="button" class="btn btn-outline-danger text-white py-2">Read More</button>
				</div>	
			</div>

		</div>

	</div>
		
</div>

<div class="container-fluid ">
	<div class="row">
		<div class="col-md-4 ">
			<div class="feature-item-1 set-bg ">
				<h3 class="fw-bolder text-white">GROUP CLASSES</h3>
				<p class="fw-light text-white ">The Sopranos manages to address the biases<br> and benefits of therapy</p>
				<button type="button" class="btn btn-outline-danger text-white">Read More</button>
			</div>
		</div>
		<div class="col-md-4">
			<div class="feature-item-2 set-bg">
				<h3 class="fw-bolder text-white">PERSONAL TRAINING</h3>
				<p class="fw-light text-white ">The Sopranos manages to address the biases<br> and benefits of therapy</p>
				<button type="button" class="btn btn-outline-danger text-white">Read More</button>
			</div>
			
		</div>
		<div class="col-md-4">
			<div class="feature-item-3 set-bg">
				<h3 class="fw-bolder text-white">SPORTS NUTRITION</h3>
				<p class="fw-light text-white ">The Sopranos manages to address the biases<br> and benefits of therapy</p>
				<button type="button" class="btn btn-outline-danger text-white">Read More</button>
			</div>			
			
		</div>
	</div>
</div>	

app/views/home/pricing.html.erb
<h4>Pricing</h4>

<div class= "conainer">
	<h4>Basic Plan</h4>
	<%= form_tag purchase_checkouts_path, method: :post, data:{turbo: false} do %>
		<input type="hidden" name="price_id" value="<%=Rails.application.credentials.dig(:stripe,:basic_pricing,:monthly)%>"/>
		<input type="submit" value="Buy Now" class="btn btn-outline-danger"/>
	<%end%>		
</div>

<br>


<div class= "conainer">
	<h4>Premium Plan</h4>
	<button type="button" class="btn btn-outline-danger">Buy Now</button>
</div>


<br>

<div class= "conainer">
	<h4>Exclusive Plan</h4>
	<button type="button" class="btn btn-outline-danger">Buy Now</button>
</div>